dependencies:
- name: dreamteam-hello
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.163
- name: dreamteam-public-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.580
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- alias: dreamteam-public-api-a
  name: dreamteam-public-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.580
- alias: dreamteam-public-api-b
  name: dreamteam-public-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.567
