dependencies:
- name: dreamteam-hello
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.77
- name: dreamteam-public-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.357
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.85
